config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :properties do
    resources :sales, only: %i[create show]
    collection do
      get :my
    end

  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :user
  has_many :sales, dependent: :destroy
  has_many_attached :photos
  geocoded_by :address
  # Incluir as validações dos campos
  validates :title, :description, :address, :photos, presence: true
  validates :price, presence: true, numericality: { only_float: true }
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :user
  belongs_to :property

  validates :user_id, uniqueness: { scope: :property_id }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  has_many :properties
  has_many :sales
  validates :first_name, :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end

  include Pundit
  after_action :verify_authorized, except: [:index], unless: :skip_pundit?
  after_action :verify_policy_scoped, only: [:index], unless: :skip_pundit?

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_property, only: %i[show edit update destroy]

  def index
    policy_scope(Property).order(created_at: :asc)

    @properties = Property.includes(:sales).where(sales: { property_id: nil })

    if params[:query].present?
      sql_query = "title ILIKE :query OR address ILIKE :query"
      @properties = @properties.where(sql_query, query: "%#{params[:query]}%")
    else
      @properties
    end

    if params[:type].present?
      sql_query = "title ILIKE :query"
      @properties = @properties.where(sql_query, query: "%#{params[:type]}%")
    else
      @properties
    end

  end

  def my
    @properties = Property.where(user_id: current_user.id)
    authorize @properties
  end

  def show
    @property = Property.find(params[:id])

    @markers = {
        lat: @property.latitude,
        lng: @property.longitude,
        info_window: render_to_string(partial: "info_window", locals: { flat: @property }),
        image_url: helpers.asset_url("home-icon.png")
        }

    @sale = Sale.new
    authorize @property
  end

  def new
    @property = Property.new
    authorize @property
  end

  def create
    @property = Property.new(property_params)
    @property.user = current_user
    authorize @property
    if @property.save
      redirect_to property_path(@property)
    else
      render :new
    end
  end

  def edit
    @property = Property.find(params[:id])
    authorize @property
  end

  def update
    @property = Property.find(params[:id])
    authorize @property
    @property.update(property_params)

    redirect_to @property
  end

  def destroy
    @property = Property.find(params[:id])
    authorize @property
    @property.destroy
    redirect_to properties_path
  end

  private

  def property_params
    params.require(:property).permit(:title, :description, :address, :price, photos: [])
  end

  def set_property
    @property = Property.find(params[:id])
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  def create
    @sale = Sale.new
    @property = Property.find(params[:property_id])
    @sale.property = @property
    @sale.user = current_user

    if @sale.save
      redirect_to property_sale_path(@property, @sale)
    else
      render 'properties/show'
    end
    skip_authorization
  end

  def show
    @sale = Sale.find(params[:id])
    @property = Property.find(params[:property_id])
    @property.user = current_user
    @property.save
    skip_authorization
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SetimoAndar</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= favicon_link_tag 'favicon-16x16.png' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(to right, rgba(0, 0, 0, 0.6), rgba(0, 0, 0, 0.8)), url(https://images.unsplash.com/photo-1568605114967-8130f3a36994);">
  <div class="container">
      <h1 class="d-flex justify-content-center" ><span data-controller="typed-js"></span></h1>
      <p class="d-flex justify-content-center"> <%= link_to "Encontre seu lar", properties_path, class: "btn btn-flat" %></p>
  </div>
</div>

<div class="container">
  <div class="information">
    <h2 class="d-flex justify-content-center">O que você procura?</h2>
    <p class="d-flex justify-content-center">Sétimo Andar tem diversas opções pra você encontrar o imóvel perfeito!</p>
  </div>
</div>

<div class="cards-home">
  <div class="card-category-home" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6)">
    <a><%= link_to "Casas", properties_path %></a>
  </div>

  <div class="card-category-home" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1523192193543-6e7296d960e4)">
    <a><%= link_to "Apartamentos", properties_path %></a>
  </div>

  <div class="card-category-home" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1601189992152-6ef7ebb531a8)">
    <a><%= link_to "Fazendas", properties_path %></a>
  </div>

  <div class="card-category-home" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1508682641856-78948a748357)">
    <a><%= link_to "Castelos", properties_path %></a>
  </div>
</div>

app/views/properties/_info_window.html.erb
<h3><%= @property.title.capitalize %></h3>
<p><%= @property.address %></p>

app/views/properties/edit.html.erb
<h1 class="text-center mt-3">Editar anúncio</h1>

<div class="container">
  <div class="row justify-content-center mt-5">
    <div class="col-md-6">
      <%= simple_form_for(@property) do |f| %>
      <%= f.input :title  %>
      <%= f.input :description %>
      <%= f.input :address, input_html: { data: { geocoder_target: "address" }, class: "d-none" },
              wrapper_html: { data: { controller: "geocoder", geocoder_api_key_value: ENV['MAPBOX_API_KEY'] } } %>
      <%= f.input :price %>
      <%= f.input :photos, as: :file, input_html: { multiple: true } %>
      <%= f.submit 'Atualizar anúncio', class: "btn btn-default btn-primary" %>

    </div>
  </div>
</div>
<% end %>

app/views/properties/index.html.erb
<div class="search">
  <%= form_tag properties_path, method: :get do %>
  <%= text_field_tag :query,
    params[:query],
    class: "search__text",
    placeholder: "Encontre um lar"
  %>
  <%= button_tag(type: "submit", class: "search__button") do  %>
    <i class="fas fa-search"></i>
  <% end %>
  <% end %>
</div>

  <div class="row m-0 p-3">
    <% @properties.each_with_index do |property, index| %>
      <div class="col-3">
        <%= link_to property_path(property) do %>
          <div class="card-trip my-2">
            <div id= <%= "carouselExampleControls#{index}" %>  class="carousel slide" data-bs-interval="false">
              <div class="carousel-inner">

               <% property.photos.each_with_index do |photo, index| %>
                <div class="carousel-item carousel-item-index <%= index == 0 ? 'active' : '' %>">
                  <%= cl_image_tag photo.key, height: 200, class: "w-100" %>
                 </div>
              <% end %>
              </div>

              <button class="carousel-control-prev" type="button" data-bs-target=<%= "#carouselExampleControls#{index}" %> data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
              </button>
              <button class="carousel-control-next" type="button" data-bs-target=<%= "#carouselExampleControls#{index}" %> data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
              </button>
            </div>
        <% end %>
            <div class="card-trip-infos">
              <h2 class="card-trip-title"><%= property.title %></h2>
              <h2 class="card-trip-pricing"><%= number_to_currency(property.price, :unit => "R$")  %></h2>
              <p class="card-trip-address"><%= property.address %></p>
            </div>
          </div>
      </div>
    <% end %>
  </div>

app/views/properties/my.html.erb
<div class="container">
  <div class="row">
    <% if @properties.count == 0 %>
      <h1 class="mt-5">You don't have any propeties yet :&#40;</h1>
    <% else %>
      <div class="properties-created mt-3">
        <h1>Propriedades criadas</h1>
        <% @properties.each do |property| %>
          <% if property.sales.empty? %>
            <div class="card-product-sale mb-3 mt-3">
              <% if property.photos.attached? %>
                <%= cl_image_tag property.photos.first.key %>
              <% else %>
                <%= image_tag("interior-unsplash.jpg") %>
              <% end %>
              <div class="card-product-infos-sale d-flex flex-column justify-content-between">
                <div class="title-info">
                  <h2><%= property.title.capitalize %></h2>
                  <p><strong><%= property.address %></strong></p>
                </div>
                <p><%= property.description %></p>
                <p><strong><%= number_to_currency(property.price, :unit => "R$") %></strong></p>
                <div class="btns-card d-flex">
                  <% if policy(property).edit? %>
                    <%= link_to 'Editar', edit_property_path(property), class: 'btn btn-warning' %>
                  <% end %>
                  <% if policy(property).destroy? %>
                    <%= link_to 'Deletar', property_path(property), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger' %>
                  <% end %>
                  <% if property.user != current_user %>
                    <%= link_to 'Comprar',  property_sales_path(property), method: :post, data: { confirm: "Are you sure?" }, class: 'btn btn-success' %>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="row">
      <div class="properties-bought mt-3">
        <h1>Propriedades compradas</h1>
        <% @properties.each do |property| %>
          <% if property.sales.empty? %>
            <% next %>
          <% else %>
            <div class="card-product-sale mb-3 mt-3">
              <% if property.photos.attached? %>
                <%= cl_image_tag property.photos.first.key %>
              <% else %>
                <%= image_tag("interior-unsplash.jpg") %>
              <% end %>
              <div class="card-product-infos-sale d-flex flex-column justify-content-between">
                <div class="title-info">
                  <h2><%= property.title.capitalize %></h2>
                  <p><strong><%= property.address %></strong></p>
                </div>
                <p><%= property.description %></p>
                <p><strong><%= number_to_currency(property.price, :unit => "R$") %></strong></p>
                <div class="btns-card d-flex">
                  <% if policy(property).edit? %>
                    <%= link_to 'Editar', edit_property_path(property), class: 'btn btn-warning' %>
                  <% end %>
                  <% if policy(property).destroy? %>
                    <%= link_to 'Deletar', property_path(property), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger' %>
                  <% end %>
                  <% if property.user != current_user %>
                    <%= link_to 'Comprar',  property_sales_path(property), method: :post, data: { confirm: "Are you sure?" }, class: 'btn btn-success' %>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/properties/new.html.erb
<h1 class="text-center mt-3">Cadastrar nova propriedade</h1>

<div class="main_section d-flex justify-content-around align-items-start">
  <div class="row mt-3">
  <%= image_tag "create-property.svg", class: "col-6" %>
    <div class="col-md-6">
      <%= simple_form_for(@property) do |f| %>
      <%= f.input :title  %>
      <%= f.input :description %>
      <%= f.input :address, input_html: { data: { geocoder_target: "address" }, class: "d-none" },
              wrapper_html: { data: { controller: "geocoder", geocoder_api_key_value: ENV['MAPBOX_API_KEY'] } } %>
      <%= f.input :price %>
      <%= number_to_currency(@property.price, :unit => "R$") %>
       <%= f.input :photos, as: :file, input_html: { multiple: true } %>
       <div class="row text-center">
        <%= f.submit 'Criar propriedade', class: "btn btn-default btn-primary" %>
      </div>
    </div>
  </div>
</div>

<% end %>

app/views/properties/show.html.erb
<div class="container">


  <div class="mt-3">
  </div>

  <div class="card-product-show mb-3">
  <div class="card-product-carousel">
    <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
      <div class="carousel-inner">
        <% @property.photos.each_with_index do |photo, index| %>
          <div class="carousel-item carousel-item-show <%= index == 0 ? 'active' : '' %>">
            <%= cl_image_tag photo.key, height: 300, width: 500, crop: :fill %>
          </div>
        <% end %>
      </div>

      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
  </div>

    <div class="card-product-infos-show d-flex flex-column justify-content-between">
      <div class="title-info">
        <h2><%= @property.title.capitalize %></h2>
        <p><strong><%= @property.address %></strong></p>
      </div>
      <p><%= @property.description %></p>
      <p><strong><%= number_to_currency(@property.price, :unit => "R$") %></strong></p>
      <div class="btns-card d-flex">
        <% if policy(@property).edit? %>
          <%= link_to 'Editar', edit_property_path(@property), class: 'btn btn-warning' %>
        <% end %>

        <% if policy(@property).destroy? %>
          <%= link_to 'Deletar', property_path(@property), method: :delete, data: { confirm: "Tem certeza que deseja deletar?" }, class: 'btn btn-danger' %>
        <% end %>
        <% if @property.user != current_user %>
          <%= link_to 'Comprar',  property_sales_path(@property), method: :post, data: { confirm: "Tem certeza que deseja comprar?" }, class: 'btn btn-success' %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="border" style="width: 100%; height: 500px;"
  data-controller="mapbox"
  data-mapbox-markers-value="<%= @markers.to_json %>"
  data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>

</div>

app/views/sales/new.html.erb
<%= @sale.user %>
<%= @sale.property %>

app/views/sales/show.html.erb
<div class="container">
  <div class="row">
    <div class="sale-text my-3">
      <h1>Parabéns pela compra!</h1>
      <h3><span class="property-name text-warning"><%= @sale.property.title %></span> agora é sua propriedade :&#41;</h3>
    </div>
    <div class="box-sale-images d-flex">
      <% if @property.photos.attached? %>
        <% if @property.photos.length >= 3 %>
          <%= cl_image_tag @property.photos.first.key, class: "sale-image big-image" %>
          <div class="box-sale-images-small d-flex flex-column">
            <%= cl_image_tag @property.photos[1].key, class: "sale-image right-image" %>
            <%= cl_image_tag @property.photos[2].key, class: "sale-image right-image" %>
          </div>
        <% else %>
          <%= cl_image_tag @property.photos.first.key, class: "sale-image big-image" %>
        <% end %>
      <% else %>
        <%= image_tag "interior-unsplash.jpg", class: "sale-image big-image" %>
        <div class="box-sale-images-small d-flex flex-column">
          <%= image_tag "interior-unsplash.jpg", class: "sale-image right-image" %>
          <%= image_tag "interior-unsplash.jpg", class: "sale-image right-image" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="container">
  <footer class="py-5">
    <div class="row">
      <div class="col-2">
        <h5>App</h5>
        <ul class="nav flex-column">
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Download Android</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Download IOS</a></li>
        </ul>
      </div>

      <div class="col-2">
        <h5>Corporativo</h5>
        <ul class="nav flex-column">
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Contatos</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Localização</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Eventos</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Parcerias</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Central de ajuda</a></li>
        </ul>
      </div>

      <div class="col-2">
        <h5>Plataforma</h5>
        <ul class="nav flex-column">
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Home</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Funcionalidades</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Preços</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Perguntas frequentes</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Sobre nós</a></li>
        </ul>
      </div>

      <div class="col-4 offset-1">
        <form>
          <h5>Se inscreva na nossa newsletter</h5>
          <p>Aproveite o conteúdo incrível</p>
          <div class="d-flex w-100 gap-2">
            <label for="newsletter1" class="visually-hidden">Endereço de e-mail</label>
            <input id="newsletter1" type="text" class="form-control" placeholder="E-mail">
            <button class="btn btn-primary" type="button">Inscrever</button>
          </div>
        </form>
      </div>
    </div>
    <div class="d-flex justify-content-between py-4 my-4 border-top">
      <p>© 2022 - 7 Andar. Todos os direitos reservados.</p>

      <div class="footer-avatars">
        <h4 class="mb-3">Nosso time:</h4>
        <ul class="list-unstyled d-flex gap-3">
          <li><a href="https://github.com/bdellacoletta" target="_blank""><%= image_tag "avatar-branca.jpg", class: "avatar-footer rounded-circle" %></a></li>
          <li><a href="https://github.com/BrunoShingai" target="_blank""><%= image_tag "avatar-bruno.jpg", class: "avatar-footer rounded-circle" %></a></li>
          <li><a href="https://github.com/igorRicci" target="_blank""><%= image_tag "avatar-igor.jpg", class: "avatar-footer rounded-circle" %></a></li>
          <li><a href="https://github.com/matheusfortini7" target="_blank""><%= image_tag "avatar-matheus.jpg", class: "avatar-footer rounded-circle" %></a></li>
        </ul>
      </div>
    </div>
  </footer>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon border-bottom border-white">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "setimo-andar.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to 'Home', root_path, class: "nav-link"  %>
          </li>
          <li class="nav-item active">
            <%= link_to 'Propriedades', properties_path, class: "nav-link"  %>
          </li>
           <li class="nav-item active">
            <%= link_to "Olá, #{current_user.first_name}!", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "home-avatar.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Minhas propriedades", my_properties_path, class: "dropdown-item" %>
              <%= link_to "Cadastrar nova propriedade", new_property_path, class: "dropdown-item" %>
              <%= link_to "Sair", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Entrar", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>